version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
      - "discovery.type=single-node"
      - "xpack.security.enabled=true"
      - "ELASTIC_USERNAME=elastic"
      - "ELASTIC_PASSWORD=elastic"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.1
    container_name: logstash
    environment:
      - "LS_JAVA_OPTS=-Xms108m -Xmx108m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
    ports:
      - "5014:5014/udp"
    depends_on:
      - elasticsearch
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=elastic"
      - "xpack.license.self_generated.type=basic"

    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  elasticsearch-data:
